# -*- coding: utf-8 -*-
"""통계분석시각화 - Numpy 활용하는 곳.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdP3lOd4z4pLAPfefwN1CMQsrZUPw4GQ

# 영상 처리
"""

import cv2 #OpenCV 라이브러리를 사용하기 위한 구문
from google.colab.patches import cv2_imshow #코랩에서 시각화를 위해 필요한 구문

cv2.__version__

path = '/content/drive/MyDrive/files/eh.jpg'
image = cv2.imread(path,cv2.IMREAD_COLOR)
cv2_imshow(image)

print(type(image))

print(image.shape)

"""# 빈 이미지 만들어서 작업하기"""

import numpy as np
image = np.zeros((28,28,3),np.uint8)

cv2_imshow(image)

print(image)

image[:,:,0]=255
print(image)

image[:,:,2]=255
cv2_imshow(image)

from tensorflow import keras

data = keras.datasets.mnist.load_data()
print(type(data))
print(len(data))

train_data, test_data = data #학습터 데이터와 평가용 데이터
print(type(train_data))
print(len(train_data))

image_train, label_train = train_data #이미지 데이터와 정답 데이터
print(image_train.shape)
print(label_train.shape)

image = image_train[0]
cv2_imshow(image)

label = label_train[0]
print(label)