# -*- coding: utf-8 -*-
"""파이썬 - 조건문 - if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wb_yPVH7_4nsWDsvhVZRXDIPtsrPh37R

# 조건문 if

if expression:

....statement 

expressio이 참일 때 statement 수행
"""

num1 = int(input("국어점수:"))
if num1>=90:
  print("A") #조건이 참일 때 수행하는 구문
  print("Good")#조건이 참일 때 수행하는 구문
print("끝~")

import datetime

now = datetime.datetime.now()
if now.hour<12:
  print('오후가 아닙니다.')
print(now.hour)

now = datetime.datetime.now()
if (now.month==1)or(now.month==2)or(now.month==12):
  print('겨울')
if (now.month==3)or(now.month==4)or(now.month==5):
  print('봄')
if (now.month==6)or(now.month==7)or(now.month==8):
  print('여름')
if (now.month==9)or(now.month==10)or(now.month==11):
  print('가을')