# -*- coding: utf-8 -*-
"""파이썬 - 출력.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJ-bC6nGSBnjY-NIKB4A2vAgsVspfazB

# 출력 기본
"""

print(12)
print(12.3)
print('hello')

print(12,12.3,'hello')

"""# format 사용"""

print("{0} abc {1} bbc {0} aaa {2} bbb {0}".format('홍길동','강감찬','을지문덕'))

print("{0:3d}".format(12))
print("{0:10d}".format(12))

print("{0:010d}".format(12))

print("{0:+10d}".format(-12))
print("{0:+10d}".format(12))

print("{0:15.2f}".format(3/2))

print("{0:3o} {0:3d} {0:3x}".format(12))

"""# f"문자열""""

num = 23
name = "홍길동"
height = 185.3
weight = 89 
print(f"번호는 {num} 이름은 {name} 키는 {height} 몸무게{weight}")