# -*- coding: utf-8 -*-
"""파이썬 - 조건문 - bool 자료형 및 관련 연산자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-67QH4Mf6EmXOfXeZ64cNJfzT4lLWYk
"""

type(False)

"""# 비교 연산자"""

i = int(input("정수:"))
i % 2 == 0

i = int(input("정수:"))
i % 2 != 0

num1 = int(input("정수:"))
num2 = int(input("정수:"))
num1<num2, num1<=num2, num1>num2, num1>=num2

"""# 논리 연산자"""

num1 = int(input("정수:"))
num2 = int(input("정수:"))
(num1 %2 == 0)and (num2 % 2 ==0)

num1 = int(input("정수:"))
num2 = int(input("정수:"))
(num1 %2 == 0) or (num2 % 2 ==0)

num1 = int(input("정수:"))
not (num1 %2 == 0)