# -*- coding: utf-8 -*-
"""파이썬 - 문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAEgTHLm4mUuOtQoPsR5vUYbH8EXJC9_
"""

s1 = "abcdefghijklmnopqrstuvwxyzABCDEFG"

len(s1) #길이

s1.upper()

s1

s1.lower()

s1

s1[16]

s1 = "           abcad     "
s1.strip()

"adsfaf123 adfaf".isalnum(),"adsfaf123adfaf".isalnum(),"ads#123adfaf".isalnum(),"123adfaf".isalnum()

s1 = "I am a boy. You are a girl. HelLovenus~"
s1.find("a "), s1.rfind("a ")

"Hello" in s1

res = s1.split(' ')
res