# -*- coding: utf-8 -*-
"""파이썬 - 반복문 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tozTLrAH4I4ZokB2JzC6QT4zbaytkkM-

# 튜플

여러 개의 원소로 구성한 자료구조(컬렉션)

원소의 값을 변경할 수 없다.
"""

tup1 = (1,)
tup2 = (1,'a')
tup3 = (1, 'abc', (2,3,'ab'))
print(tup1)
print(tup2)
print(tup3)

tup1 = (1,2,3)
print(tup1[0])
print(tup1[1])
print(tup1[2])

#tup1[0]=7 튜플은 원소의 값을 변경할 수 없다.

"""# 리스트

여러 개의 원소로 구성한 자료구조(컬렉션)

튜플과 다르게 원소의 값을 변경할 수 있다.
"""

ls1 = [1,2,3,4]
print(ls1)

ls2 = [1,2,3,'a',[1,2,3],(1,2,'a')]
print(ls2)

ls1 = [1,2,3,4,5,'a','b']
print(ls1[0])
print(ls1[1])
print(ls1[2])
print(ls1[3])
print(ls1[4])
print(ls1[5])
print(ls1[6])
#print(ls1[7]) out of range

s = "abcdefg"
print(s[1:3])

ls1 = [1,2,3,'a','b']
print(ls1[1:3]) #1~2
print(ls1[:3]) #0~2
print(ls1[1:]) #1~끝까지

tup1 = (1,2,3)
ls1 = [1,2,3]

#tup1[0]=3 원소의 값을 변경할 수 없다.
ls1[0]=3 #리스트는 원소의 값을 변경할 수 있다.
print(ls1[0])

ls1 = [1,2,3,4,5,6]
print(ls1[-1])
print(ls1[-2])
print(ls1[-3])
print(ls1[-4])
print(ls1[-5])
print(ls1[-6])

ls1 = [[90,80,45],[88,95,64],[99,64,89]]
print(ls1[0])
print(ls1[0][2])

ls1 = [1,2,3]
ls2 = ['a','b','c']
print(ls1+ls2)

print(ls1)
print(ls2)
ls3 = ls1+ls2
print(ls3)

ls1 = [1,2,3]
ls2 = ['a','b','c']
print(ls1*3)
s1 = "홍길동"
print(s1*3)

print(len('abcdefghijklmnopqrstuvwxyz'))
print(len([1,2,3,4,5,6,7,8,9,10,'a','b']))

"""# 리스트에 순차 보관"""

ls1 = list() #빈 리스트 생성하기
print(ls1)
print(type(ls1))

ls1.append(3)
ls1.append(7)
ls1.append(2)
ls1.append(8)
print(ls1)

"""# 리스트 - 원하는 위치에 보관"""

ls=[1,2,4,5,6,7]
num = 3
ls.insert(2,num)
print(ls)

"""# 리스트 병합"""

ls1 = [1,2,3]
ls2 = ['a','b','c']
print(ls1+ls2)

print(ls1)
print(ls2)
ls3 = ls1+ls2
print(ls3)

ls1 = [1,2,3]
ls2 = ['a','b','c']
print(ls1.extend(ls2)) #반환 값은 없음
print(ls1) #ls1의 결과가 바뀐 것을 알 수 있음
print(ls2)

"""# 리스트 - 요소 제거하기

append로 추가하고 pop으로 꺼내면 stack처럼 동작한다.

LIFO(Last In First Out)
"""

ls1 = [1,2,3,4,5,6,7,8]
print(ls1)
re = ls1.pop()
print(re)
print(ls1)

ls1 = [1,2,3,4,5,6,7,8]
print(ls1)
re = ls1.pop(3)
print(re)
print(ls1)
re = ls1.pop(3)
print(re)
print(ls1)

ls1 = [1,2,3,4,5,6,7,8]
print(ls1)
del ls1[2]
print(ls1)
del ls1[2]
print(ls1)
del ls1[2]
print(ls1)

ls1 = [1,2,3,4,5,6,7,8]
print(ls1)
del ls1[2:]
print(ls1)

member_list = ['홍길동','강감찬','을지문덕','고길동','김구','음냐뤼']

print(member_list)
name = input("지울 회원:")
member_list.remove(name)
print(member_list)

member_list = ['홍길동','강감찬','을지문덕','고길동','김구','음냐뤼']

print(member_list)
member_list.clear()
print(member_list)

s = "나는 집에 간다. 그리고 나는 잠을 잔다."
print("간다" in s)

member_list = ['홍길동','강감찬','을지문덕','고길동','김구','음냐뤼']
name = input("검색할 회원:")
if name in member_list:
  print("존재합니다.")
else:
  print("아직 회원이 아닙니다.")