# -*- coding: utf-8 -*-
"""파이썬 - 시작하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/ehpub/7069afbb20ccde8909d35f0b2749a29a/.ipynb

# 계산
"""

23+4

"""# 명명"""

korea = 90
math = 80
sum = korea+math
sum

"""# 주석"""

#주석
a = 3 #변수 a에 3 대입
a

"""# 출력문"""

print(12)
print("음냐뤼")
print(12,3,"야호")

print("진달래꽃")
print()
print("나 보기가 역겨워")