# -*- coding: utf-8 -*-
"""파이썬 - 반복문(딕셔너리).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2CYD_57WbN3wVA6XYjzf10YKTvrYYuX

# 딕셔너리

키와 값을 쌍으로 갖는 요소를 보관하는 자료구조(컬렉션)
"""

member_states={"홍길동":23,
               "강감찬":17,
               "을지문덕":89}
print(member_states)

print(member_states["홍길동"])

subjects =("국어","영어","수학")
scores_dic = {}
for i in range(2):
  name = input(f"{i+1}번째 학생 이름:")
  scores=[]
  for s in subjects:
    score = int(input(f"{s}:"))
    scores.append(score)
  scores_dic[name] = scores #값 추가 or 변경
print(scores_dic)

name = input("삭제할 학생:")
del scores_dic[name]
print(scores_dic)

eh_att_dic ={}
eh_att_dic["title"]="언제나휴일"
eh_att_dic["url"]="http://ehpub.co.kr"
eh_att_dic["desc"]="어쩌구 저쩌구"
print(eh_att_dic)

#print(eh_att_dic["score"]) 존재하지 않는 키를 인덱스 연산으로 사용하면 KeyError 발생

if "url" in eh_att_dic:
  print(f'존재합니다. url:{eh_att_dic["url"]}')
else:
  print("url 정보가 없습니다.")

value = eh_att_dic.get("url")
if value == None:
  print("url 정보가 없습니다.")
else:
  print(f"url:{value}")

value = eh_att_dic.get("score")
if value == None:
  print("score 정보가 없습니다.")
else:
  print(f"score:{value}")

for attr in eh_att_dic:
  print(f"{attr}:{eh_att_dic[attr]}")