# -*- coding: utf-8 -*-
"""파이썬 - 자료형 - 문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnX5YIUsnQRUOLWFGRTg2S_PgKBr0dqC

# 문자열 기본 표현
"""

print('abc')
print("ABC")
print("""안녕하세요.""")

"""# 이스케이프 문자"""

print('\t하이')
print('우리는\t야호\n하하하')

print('I\'m a boy.')

print("I'm a boy.")

print("그가 \"안녕\"이라고 말했다.")

print('그가 "안녕"이라고 말했다.')

"""# 인용문"""

print("===")
azale ="""
나 보기가 역겨워
가실 때에는
말없이 고이 보내
드리오리다.
"""
print(azale)
print("===")

print("===")
azale2 ="""\
나 보기가 역겨워
가실 때에는
말없이 고이 보내
드리오리다.\
"""
print(azale2)
print("===")

"""# 문자 코드"""

print("a:",ord('a'),"A:",ord('A'),"0:",ord('0')) #'a':0110 0001 'A':0101 0001 '0':0011 0001

print(chr(97),chr(65),chr(48))